branch-defaults:
  default:
    environment: react321-venv
  master:
    environment: react321-venv
environment-defaults:
  react321-venv:
    branch: master
    repository: saleor-platform-multi
global:
  application_name: react321
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
